name: Frontend Deploy to S3

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Upload to S3
      - name: Upload Frontend to S3
        run: |
          aws s3 sync frontend/ s3://devops-frontend-suhas --delete

      # Make files public
      - name: Set Public Read Permissions
        run: |
          aws s3 cp s3://devops-frontend-suhas \
            s3://devops-frontend-suhas \
            --recursive \
            --acl public-read

      # Output URL
      - name: Show Website URL
        run: |
          echo "Frontend URL:"
          echo "http://devops-frontend-suhas.s3-website-ap-south-1.amazonaws.com"

